/* Koine Greek — service worker.

   The app is a handful of static files, so the strategy is cache-first: a hit means
   it opens instantly and works with no connection at all, and a miss only
   happens on first run. Bump VERSION to ship a change — the old cache is
   dropped on activate and the page is offered a reload.

   Off-origin requests (YouTube, billmounce.com) are deliberately not touched.
   Those are the pronunciation resources and they need a connection; the app
   greys them out when offline rather than caching a broken copy. */

const VERSION = 'v212';
const CACHE   = `koine-${VERSION}`;

/* The bulk set — 470 word clips and 27 New Testament books, 497 files and
   9.5MB — lives in its own cache. One cache name swept on every VERSION bump
   meant every code change threw all of it away and pulled it down again,
   with "Hear it" and the reader failing offline until the refill finished.
   Bump this digit only when a bulk file's *content* changes.

   Safe to keep across versions: the mp3 filenames encode VOCAB array indices
   and data/vocab.js is append-only, so a kept cache can only ever be missing
   newly added files — which the next fill adds. It can never map an old file
   onto a new index. */
const BULK = 'koine-bulk-1';
const isBulkUrl = u => /audio\/vocab\/[^/]+\.mp3$/.test(u)
                    || /audio\/lessons\/[^/]+\.mp3$/.test(u)
                    || /data\/gnt\/(?!manifest\.json)[^/]+\.json$/.test(u);

/* Bulk files whose *content* changed in this release. The bulk cache is
   deliberately never swept, so a re-recorded clip would otherwise be served
   from it for ever — the fill only fetches what is missing. Evicting the few
   that changed costs two small re-downloads instead of all 9.5MB, which is
   what bumping BULK would cost. Empty this list in the release after the
   one that fills it. */
const STALE = [
  /* v212: χήρα, on the χρεία ending undotted -- the same fix Ἀντιόχεια
     took a lot earlier. It is the 817th of the deck's 818 cues to have been
     through an ear; εὐλογία is the last one out. */
  'audio/vocab/550_chera.mp3',
  'audio/vocab/744_eulogia.mp3',
  /* v211: batch 25R, eight of ten -- the ten that 25Q had sent with
     pre-rule cues, re-cued with the rules actually applied. Every chi came
     back right as a k and every epsilon right as ɛ, which is the rules
     working and the freeze having been the whole fault. ὦ is the one to
     note: the ear confirmed it has NO h, and the cue shipping until now
     was "hoe". */
  'audio/vocab/698_antiocheia.mp3',
  'audio/vocab/705_katecho.mp3',
  'audio/vocab/717_charisma.mp3',
  'audio/vocab/733_o.mp3',
  'audio/vocab/798_prolego.mp3',
  'audio/vocab/806_chortazo.mp3',
  'audio/vocab/808_anechomai.mp3',
  'audio/vocab/812_epimeno.mp3',
  /* v210: batch 25Q, thirty-eight of forty-eight. The ten that failed were
     sent with PRE-RULE cues -- settled.py let a screen fix count as settled
     alongside an ear approval, which froze them against the 25O inventory
     and the v209 chi rule. They failed for faults already fixed. It now
     holds ear approvals only. */
  'audio/vocab/706_kataluo.mp3',
  'audio/vocab/709_meti.mp3',
  'audio/vocab/711_peritemno.mp3',
  'audio/vocab/712_pleroma.mp3',
  'audio/vocab/713_plesion.mp3',
  'audio/vocab/714_potamos.mp3',
  'audio/vocab/715_skotia.mp3',
  'audio/vocab/716_tarasso.mp3',
  'audio/vocab/720_apokalupsis.mp3',
  'audio/vocab/743_dipsao.mp3',
  'audio/vocab/746_kakos.mp3',
  'audio/vocab/747_katakrino.mp3',
  'audio/vocab/750_kan.mp3',
  'audio/vocab/753_oudepote.mp3',
  'audio/vocab/754_pathema.mp3',
  'audio/vocab/755_parecho.mp3',
  'audio/vocab/759_sullambano.mp3',
  'audio/vocab/761_teras.mp3',
  'audio/vocab/762_tolmao.mp3',
  'audio/vocab/764_atheteo.mp3',
  'audio/vocab/765_anakrino.mp3',
  'audio/vocab/769_epeita.mp3',
  'audio/vocab/770_ephesos.mp3',
  'audio/vocab/771_ustereo.mp3',
  'audio/vocab/775_geuomai.mp3',
  'audio/vocab/792_oikoumene.mp3',
  'audio/vocab/796_perissoteros.mp3',
  'audio/vocab/797_potizo.mp3',
  'audio/vocab/799_saleuo.mp3',
  'audio/vocab/800_skandalon.mp3',
  'audio/vocab/801_sumphero.mp3',
  'audio/vocab/802_sunistemi.mp3',
  'audio/vocab/803_sphragizo.mp3',
  'audio/vocab/804_trapeza.mp3',
  'audio/vocab/805_tupos.mp3',
  'audio/vocab/809_anomia.mp3',
  'audio/vocab/810_apago.mp3',
  'audio/vocab/811_epaggellomai.mp3',
  /* v209: batch 25P, FORTY-NINE OF FIFTY-ONE, the first round generated by
     the corrected inventory rather than patched afterwards -- and NOT ONE
     epsilon failure, where that fault had produced seven of thirteen two
     rounds earlier. Chi is now a plain k wherever it stands: Fraser, on
     χήρα failing a third time, "if χ can't be consistent perhaps we should
     just replace it with a k sound", and the record agrees -- k won twice,
     x failed three times. */
  'audio/vocab/501_timao.mp3',
  'audio/vocab/509_pote.mp3',
  'audio/vocab/556_aiguptos.mp3',
  'audio/vocab/559_keleuo.mp3',
  'audio/vocab/561_mepote.mp3',
  'audio/vocab/573_keimai.mp3',
  'audio/vocab/574_nous.mp3',
  'audio/vocab/575_pimplemi.mp3',
  'audio/vocab/576_parousia.mp3',
  'audio/vocab/578_prosecho.mp3',
  'audio/vocab/579_soter.mp3',
  'audio/vocab/582_astheneia.mp3',
  'audio/vocab/583_aster.mp3',
  'audio/vocab/584_dioti.mp3',
  'audio/vocab/585_eikon.mp3',
  'audio/vocab/587_thusiasterion.mp3',
  'audio/vocab/588_kataleipo.mp3',
  'audio/vocab/590_kopiao.mp3',
  'audio/vocab/591_koluo.mp3',
  'audio/vocab/592_mimneskomai.mp3',
  'audio/vocab/594_peinao.mp3',
  'audio/vocab/610_kakeinos.mp3',
  'audio/vocab/611_metanoia.mp3',
  'audio/vocab/614_poleo.mp3',
  'audio/vocab/615_sunedrion.mp3',
  'audio/vocab/620_auxano.mp3',
  'audio/vocab/621_basileuo.mp3',
  'audio/vocab/622_didaskalia.mp3',
  'audio/vocab/624_therizo.mp3',
  'audio/vocab/630_strepho.mp3',
  'audio/vocab/632_energeo.mp3',
  'audio/vocab/633_ephistemi.mp3',
  'audio/vocab/634_upakouo.mp3',
  'audio/vocab/637_goneus.mp3',
  'audio/vocab/656_baptisma.mp3',
  'audio/vocab/664_men.mp3',
  'audio/vocab/666_paraptoma.mp3',
  'audio/vocab/667_paratithemi.mp3',
  'audio/vocab/668_propheteia.mp3',
  'audio/vocab/669_teleios.mp3',
  'audio/vocab/670_apecho.mp3',
  'audio/vocab/671_epano.mp3',
  'audio/vocab/673_epilambanomai.mp3',
  'audio/vocab/674_epouranios.mp3',
  'audio/vocab/675_blasphemia.mp3',
  'audio/vocab/679_kataggello.mp3',
  'audio/vocab/680_kenos.mp3',
  'audio/vocab/681_kleronomeo.mp3',
  'audio/vocab/682_koimaomai.mp3',
  'audio/vocab/699_asia.mp3',
  'audio/vocab/700_epiballo.mp3',
  'audio/vocab/701_epitrepo.mp3',
  'audio/vocab/702_kaisareia.mp3',
  /* v208: THE INVENTORY TEST. Thirteen words that had failed and seven an
     ear had already approved, each re-cued with every short epsilon written
     ɛ and the first eta written as the ay-pair. The controls are what made
     it a test and one of them broke, which is the finding: εἰρήνη carried
     three ay-pairs and spelled itself out. So ɛ everywhere, and the ay-pair
     ONCE per word. Five of these thirteen are words already approved whose
     ear preferred the new cue to the one it had passed. */
  'audio/vocab/043_pater.mp3',
  'audio/vocab/054_laleo.mp3',
  'audio/vocab/135_meno.mp3',
  'audio/vocab/468_ide.mp3',
  'audio/vocab/499_merimnao.mp3',
  'audio/vocab/504_teleioo.mp3',
  'audio/vocab/557_deka.mp3',
  'audio/vocab/562_nephele.mp3',
  'audio/vocab/626_latreuo.mp3',
  'audio/vocab/627_meketi.mp3',
  'audio/vocab/635_aitia.mp3',
  'audio/vocab/649_eneken.mp3',
  'audio/vocab/692_stephanos.mp3',
  /* v207: batch 25M, forty-one of forty-three. μετά is the one to name:
     469 occurrences, the biggest word this loop has settled, and it took
     the open epsilon that περί needed for the identical complaint a
     dozen rounds ago. 109 cues left, 2,071 occurrences -- 1.7% of what the
     deck plays. The expensive part is done. */
  'audio/vocab/038_meta.mp3',
  'audio/vocab/297_chara.mp3',
  'audio/vocab/303_mede.mp3',
  'audio/vocab/327_ara.mp3',
  'audio/vocab/329_graphe.mp3',
  'audio/vocab/332_apodidomi.mp3',
  'audio/vocab/342_ouketi.mp3',
  'audio/vocab/350_dioko.mp3',
  'audio/vocab/355_katoikeo.mp3',
  'audio/vocab/360_seautou.mp3',
  'audio/vocab/363_phoneo.mp3',
  'audio/vocab/368_luo.mp3',
  'audio/vocab/375_semeron.mp3',
  'audio/vocab/404_peirazo.mp3',
  'audio/vocab/409_orge.mp3',
  'audio/vocab/410_arti.mp3',
  'audio/vocab/418_peritome.mp3',
  'audio/vocab/426_upostrepho.mp3',
  'audio/vocab/430_mete.mp3',
  'audio/vocab/433_astheneo.mp3',
  'audio/vocab/439_arneomai.mp3',
  'audio/vocab/448_upomone.mp3',
  'audio/vocab/451_katharizo.mp3',
  'audio/vocab/453_poterion.mp3',
  'audio/vocab/457_phulasso.mp3',
  'audio/vocab/458_phule.mp3',
  'audio/vocab/462_sunerchomai.mp3',
  'audio/vocab/463_skandalizo.mp3',
  'audio/vocab/466_agorazo.mp3',
  'audio/vocab/492_sos.mp3',
  'audio/vocab/542_mariam.mp3',
  'audio/vocab/543_douleuo.mp3',
  'audio/vocab/544_katharos.mp3',
  'audio/vocab/545_lupeo.mp3',
  'audio/vocab/546_oupo.mp3',
  'audio/vocab/548_suniemi.mp3',
  'audio/vocab/549_phroneo.mp3',
  'audio/vocab/551_apokalupto.mp3',
  'audio/vocab/553_iaomai.mp3',
  'audio/vocab/554_omnuo.mp3',
  'audio/vocab/555_omologeo.mp3',
  /* v206: batch 25L, THIRTY-SEVEN OF FORTY and the biggest round yet.
     These are the forty most frequent cues still unheard, 5,723
     occurrences installed here -- and the reason forty was the right size
     is that what remains is top-heavy: 41 cues carried two thirds of the
     exposure and 146 carry the other third. μετά at 469 occurrences is
     among the three that failed, so it is not here. */
  'audio/vocab/040_akouo.mp3',
  'audio/vocab/043_pater.mp3',
  'audio/vocab/044_emera.mp3',
  'audio/vocab/052_eautou.mp3',
  'audio/vocab/054_laleo.mp3',
  'audio/vocab/059_ge.mp3',
  'audio/vocab/065_apokrinomai.mp3',
  'audio/vocab/068_upo.mp3',
  'audio/vocab/072_te.mp3',
  'audio/vocab/073_dunamai.mp3',
  'audio/vocab/075_outos.mp3',
  'audio/vocab/083_kathos.mp3',
  'audio/vocab/092_basileia.mp3',
  'audio/vocab/106_kaleo.mp3',
  'audio/vocab/136_aperchomai.mp3',
  'audio/vocab/138_agape.mp3',
  'audio/vocab/142_krino.mp3',
  'audio/vocab/147_aletheia.mp3',
  'audio/vocab/154_ekei.mp3',
  'audio/vocab/160_airo.mp3',
  'audio/vocab/166_tithemi.mp3',
  'audio/vocab/176_enopion.mp3',
  'audio/vocab/181_eirene.mp3',
  'audio/vocab/183_kathemai.mp3',
  'audio/vocab/188_oute.mp3',
  'audio/vocab/195_kago.mp3',
  'audio/vocab/199_upago.mp3',
  'audio/vocab/211_euaggelizo.mp3',
  'audio/vocab/222_epaggelia.mp3',
  'audio/vocab/238_an.mp3',
  'audio/vocab/240_ote.mp3',
  'audio/vocab/243_archo.mp3',
  'audio/vocab/265_pino.mp3',
  'audio/vocab/268_aiteo.mp3',
  'audio/vocab/294_uparcho.mp3',
  'audio/vocab/306_dechomai.mp3',
  'audio/vocab/322_parabole.mp3',
  /* v205: batch 25K, FIFTEEN OF FIFTEEN -- every lot, no notes, the first
     complete round of the session. διαλογίζομαι is the one to name:
     the spelling detector caught it in its first live round, spelling
     itself DIALOGI, and it was re-cut before an ear ever heard it. That is
     what "stop spelling sounds" asked for. εὐλογέω makes the secondary
     stress a rule with three cases behind it. */
  'audio/vocab/037_kata.mp3',
  'audio/vocab/135_meno.mp3',
  'audio/vocab/296_sunago.mp3',
  'audio/vocab/379_eulogeo.mp3',
  'audio/vocab/403_boulomai.mp3',
  'audio/vocab/472_epistole.mp3',
  'audio/vocab/540_eko.mp3',
  'audio/vocab/572_gnorizo.mp3',
  'audio/vocab/604_gregoreo.mp3',
  'audio/vocab/655_osei.mp3',
  'audio/vocab/696_apoleia.mp3',
  'audio/vocab/741_dialogizomai.mp3',
  'audio/vocab/780_diamarturomai.mp3',
  'audio/vocab/786_katerchomai.mp3',
  'audio/vocab/814_omoioo.mp3',
  /* v203: batch 25J, seven of twelve -- the weakest sample yet, and four
     of the five failures were the dot. τις settled at 525 occurrences,
     per-word, because the transcription cannot tell it from πρίν: both
     are written with a stressed bare i and one consonant after, and πρίν
     is right as PREEN. The pack does not mark vowel length, so no rule
     separates them -- the first limit this project has hit in its SOURCE
     rather than in its rules. */
  'audio/vocab/033_tis.mp3',
  'audio/vocab/120_duo.mp3',
  'audio/vocab/286_erotao.mp3',
  'audio/vocab/484_paraklesis.mp3',
  'audio/vocab/654_upsoo.mp3',
  'audio/vocab/692_stephanos.mp3',
  'audio/vocab/738_desmios.mp3',
  /* v202: batch 25I, ten of twelve; six samples stand at 67 of 72. The
     unheard population is 220 cues and 11,969 occurrences, NOT the 275
     quoted since batch 25B -- ipa_cue's HEARD set had never been told
     about batches 25B to 25H, so 55 words already shipped still counted
     as unheard. The coverage model now reads zero features outstanding. */
  'audio/vocab/131_ballo.mp3',
  'audio/vocab/290_ode.mp3',
  'audio/vocab/396_epitithemi.mp3',
  'audio/vocab/538_ekeithen.mp3',
  'audio/vocab/571_timotheos.mp3',
  'audio/vocab/603_makedonia.mp3',
  'audio/vocab/694_phaneros.mp3',
  'audio/vocab/740_denarion.mp3',
  'audio/vocab/781_eita.mp3',
  'audio/vocab/816_opheleo.mp3',
  /* v200: batch 25H, thirteen of thirteen, and the whole round came
     through three screening rolls with nothing flagged at all -- no spoken
     dots, no beat mismatches, no dedotting. Five frequency-spread samples
     of the population the coverage model calls safe now stand at 57 of 60.
     ἔρχομαι is here at 634 occurrences. */
  'audio/vocab/028_erchomai.mp3',
  'audio/vocab/114_oude.mp3',
  'audio/vocab/285_thelema.mp3',
  'audio/vocab/381_paristemi.mp3',
  'audio/vocab/483_klesis.mp3',
  'audio/vocab/498_epitimao.mp3',
  'audio/vocab/537_posos.mp3',
  'audio/vocab/564_pareimi.mp3',
  'audio/vocab/600_anago.mp3',
  'audio/vocab/641_xulon.mp3',
  'audio/vocab/691_polemos.mp3',
  'audio/vocab/725_existemi.mp3',
  'audio/vocab/785_thrix.mp3',
  /* v199: batch 25G, the first round screened THREE times rather than
     once. Twelve of thirteen, and four samples now stand at 45 of 48.
     γνωστός confirms the helper vowel a second time -- ɡn cannot open
     an English syllable any more than πν can, and the ear wants it said.
     ἑκατόν said its dot on all three rolls in a form the literal test
     could not see, and sharpened the detector. */
  'audio/vocab/021_echo.mp3',
  'audio/vocab/119_phone.mp3',
  'audio/vocab/215_apoluo.mp3',
  'audio/vocab/277_phemi.mp3',
  'audio/vocab/393_thura.mp3',
  'audio/vocab/503_deloo.mp3',
  'audio/vocab/570_ellen.mp3',
  'audio/vocab/596_skeuos.mp3',
  'audio/vocab/647_argurion.mp3',
  'audio/vocab/686_parachrema.mp3',
  'audio/vocab/728_ekaton.mp3',
  'audio/vocab/776_gnostos.mp3',
  /* v198: batch 25F. A THIRD frequency-spread sample, the first drawn
     after the screen was mended -- eleven of twelve, and three samples now
     stand at 34 of 36. μή is here at 1,042 occurrences. The twelfth,
     ἀπολύω, is the one that teaches: it was flagged for a spoken dot,
     CLEARED on a re-roll, and the ear heard the dot anyway. A re-roll that
     clears is not evidence the string is safe. */
  'audio/vocab/015_me.mp3',
  'audio/vocab/116_soma.mp3',
  'audio/vocab/386_miseo.mp3',
  'audio/vocab/508_axios.mp3',
  'audio/vocab/535_krima.mp3',
  'audio/vocab/567_adikia.mp3',
  'audio/vocab/568_anablepo.mp3',
  'audio/vocab/599_ampelon.mp3',
  'audio/vocab/608_katergazomai.mp3',
  'audio/vocab/645_trecho.mp3',
  'audio/vocab/689_prostithemi.mp3',
  'audio/vocab/731_upomeno.mp3',
  'audio/vocab/779_desmos.mp3',
  /* v197: batch 25E. A SECOND frequency-spread sample of the population
     the coverage model calls safe -- eleven of twelve, ten of them
     straight from the converter, ὅς at 1,407 occurrences among them. The
     twelfth failed on a spoken dot the SCREEN had stopped seeing, because
     a tolerance added hours earlier hid it; the screen now looks for the
     word "dot" by name instead of inferring it from a beat count. */
  'audio/vocab/011_os.mp3',
  'audio/vocab/109_eos.mp3',
  'audio/vocab/253_stoma.mp3',
  'audio/vocab/372_amartano.mp3',
  'audio/vocab/476_messias.mp3',
  'audio/vocab/500_nikao.mp3',
  'audio/vocab/595_periballo.mp3',
  'audio/vocab/642_proago.mp3',
  'audio/vocab/683_kopos.mp3',
  'audio/vocab/721_aresko.mp3',
  'audio/vocab/772_damaskos.mp3',
  /* v196: batch 25D. The twelve-word sample is now 12 for 12, the two
     stragglers taking one more round. βαστάζω chose the UNTIED dz over
     the tie-barred affricate the converter makes -- six approved cues
     carry that affricate and not one had ever been put against its own
     alternative. χιλιάς took a plain k at the front of a word, because
     `xi` is the English name of the letter ξ and read as a z. */
  'audio/vocab/533_bastazo.mp3',
  'audio/vocab/598_chilias.mp3',
  /* v195: batch 25C. ἀφίημι settled after five rounds, and ten of a
     twelve-word SAMPLE of the 275 cues the coverage model calls safe --
     the first honest test of whether the rules are right without an ear.
     οὐ is here at 1,606 occurrences, the second commonest word in the
     New Testament, straight from the converter with nothing changed. */
  'audio/vocab/010_ou.mp3',
  'audio/vocab/112_agapao.mp3',
  'audio/vocab/113_aphiemi.mp3',
  'audio/vocab/270_ago.mp3',
  'audio/vocab/384_etoimazo.mp3',
  'audio/vocab/505_aggello.mp3',
  'audio/vocab/569_eorte.mp3',
  'audio/vocab/644_tosoutos.mp3',
  'audio/vocab/688_pollakis.mp3',
  'audio/vocab/729_etoimos.mp3',
  'audio/vocab/784_themelios.mp3',
  /* v194: batch 25B, eight of nine, and the coverage model is closed but
     for one word. εὐαγγέλιον took a SECONDARY STRESS on its glide,
     a symbol no approved cue had carried: after three rounds of moving
     dots, what the hiatus needed was weight rather than a pause. And
     ἀντί became *aunty* by writing its short alpha long -- the colour
     the ear wanted, against the quantity the Greek has. */
  'audio/vocab/210_euaggelion.mp3',
  'audio/vocab/507_anti.mp3',
  'audio/vocab/616_tesserakonta.mp3',
  'audio/vocab/638_marturion.mp3',
  'audio/vocab/640_nuni.mp3',
  'audio/vocab/646_akrobustia.mp3',
  'audio/vocab/657_georgos.mp3',
  'audio/vocab/773_lazaros.mp3',
  /* v193: batch 25, five of eight. πνευματικός settles the helper vowel: πν
     cannot open an English syllable, the transcription writes a schwa,
     the voice may say it or not -- and the ear prefers it said. That is
     the question the screen had to be taught to stop failing. */
  'audio/vocab/510_prin.mp3',
  'audio/vocab/536_kome.mp3',
  'audio/vocab/547_pneumatikos.mp3',
  'audio/vocab/563_ou.mp3',
  'audio/vocab/607_katheudo.mp3',
  /* v192: batch 24B, seven of nine. ἰδού took its dot back, which the
     approved cues had predicted: every word-initial ɪ in the pack is
     followed by a vowel or a dot, and a shut one is the English *id*. */
  'audio/vocab/050_peri.mp3',
  'audio/vocab/076_idou.mp3',
  'audio/vocab/231_asthenes.mp3',
  'audio/vocab/309_tritos.mp3',
  'audio/vocab/343_achri.mp3',
  'audio/vocab/502_fileo.mp3',
  /* v191: batch 24. Six composed cues lost to their IPA, 780 occurrences,
     and οὐχί is the one to name: two syllables, one of them the chi, and
     writing that chi as a plain k still won. The medial-chi rule holds in
     the hardest place for it. */
  'audio/vocab/053_oida.mp3',
  'audio/vocab/080_para.mp3',
  'audio/vocab/178_oikia.mp3',
  'audio/vocab/261_dodeka.mp3',
  'audio/vocab/314_ouchi.mp3',
  'audio/vocab/334_pou.mp3',
  /* v190: batch 23, eleven of eleven. εἰμί is the one to name -- the
     commonest word in the New Testament, 2,462 occurrences, and IPA beat
     the composed cue it has always shipped. ἀπό and ἀλλά likewise. */
  'audio/vocab/007_eimi.mp3',
  'audio/vocab/026_apo.mp3',
  'audio/vocab/027_alla.mp3',
  'audio/vocab/292_ede.mp3',
  'audio/vocab/455_exesti-n.mp3',
  'audio/vocab/562_nephele.mp3',
  'audio/vocab/565_porneia.mp3',
  'audio/vocab/658_diakrino.mp3',
  'audio/vocab/677_eisporeuomai.mp3',
  'audio/vocab/690_pulon.mp3',
  'audio/vocab/767_epithumeo.mp3',
  /* v189: fifteen cues from the bulk pass, the ones a sample of twenty
     approved. Five of that twenty failed, so the other 112 are NOT
     shipping -- see the commit message. */
  'audio/vocab/480_musterion.mp3',
  'audio/vocab/521_barnabas.mp3',
  'audio/vocab/552_epei.mp3',
  'audio/vocab/577_pais.mp3',
  'audio/vocab/593_peran.mp3',
  'audio/vocab/609_kategoreo.mp3',
  'audio/vocab/625_kathistemi.mp3',
  'audio/vocab/639_nesteuo.mp3',
  'audio/vocab/652_isaak.mp3',
  'audio/vocab/687_poimen.mp3',
  'audio/vocab/710_nipto.mp3',
  'audio/vocab/737_gamos.mp3',
  'audio/vocab/749_kleio.mp3',
  'audio/vocab/778_dero.mp3',
  'audio/vocab/793_petra.mp3',
  /* v188: batch 22, ten of ten first time. The novelty list closes -- no
     unheard cue now holds a sound in a position nothing demonstrates -- and
     six of the ten were drawn at RANDOM from the 336 that hold nothing new,
     which is the population a bulk run would ship unheard. Six of six. */
  'audio/vocab/042_didomi.mp3',
  'audio/vocab/293_imation.mp3',
  'audio/vocab/382_time.mp3',
  'audio/vocab/494_leipo.mp3',
  'audio/vocab/650_egemon.mp3',
  'audio/vocab/719_anagke.mp3',
  'audio/vocab/723_elegcho.mp3',
  'audio/vocab/726_epaurion.mp3',
  'audio/vocab/752_numphios.mp3',
  'audio/vocab/783_eucharistia.mp3',
  /* v187: batch 21, all eight settled. τίκτω turned πίπτω's exception into a
     rule -- a stressed short iota shut in by TWO consonants is written ɪ --
     which leaves one sound exception in the whole pack. */
  'audio/vocab/315_dio.mp3',
  'audio/vocab/541_iakob.mp3',
  'audio/vocab/560_leukos.mp3',
  'audio/vocab/589_koilia.mp3',
  'audio/vocab/629_peirasmos.mp3',
  'audio/vocab/693_tikto.mp3',
  'audio/vocab/697_arithmos.mp3',
  'audio/vocab/703_broma.mp3',
  /* v186: batch 20. Eight clips, and the hiatus rule widened from "after an
     e" to "after any short vowel but i" -- λαός and ναός both kept a dot
     the converter was taking out. γν opening a word works, which English
     cannot write: *gnosis* has a silent g. */
  'audio/vocab/115_laos.mp3',
  'audio/vocab/218_naos.mp3',
  'audio/vocab/378_dierchomai.mp3',
  'audio/vocab/425_opheilo.mp3',
  'audio/vocab/461_parresia.mp3',
  'audio/vocab/482_gnosis.mp3',
  'audio/vocab/496_feugo.mp3',
  'audio/vocab/539_ekcheo.mp3',
  /* v185: batches 19 and 19B. Twelve clips, and θεός among them -- 1,317
     occurrences, the deck's commonest word, off an English respelling at
     last and onto a string the converter now writes unaided. */
  'audio/vocab/012_theos.mp3',
  'audio/vocab/024_dia.mp3',
  'audio/vocab/217_arnion.mp3',
  'audio/vocab/223_sperma.mp3',
  'audio/vocab/236_ean.mp3',
  'audio/vocab/278_eite.mp3',
  'audio/vocab/345_ouai.mp3',
  'audio/vocab/358_genea.mp3',
  'audio/vocab/558_dendron.mp3',
  'audio/vocab/736_kapharnaoum.mp3',
  'audio/vocab/739_deipnon.mp3',
  'audio/vocab/817_rabbi.mp3',
  /* v184: batch 18, an experiment about dots. ὅτι is the one that matters --
     the deck's commonest word, 1,296 occurrences, and the converter's own
     string beat the one it has shipped since batch 9.
     NO PATHS BELOW THIS COMMENT: all four clips -- 013, 133, 198, 271 --
     are already named in the v163, v164 and v165 blocks, so the eviction
     is covered and repeating them would only be noise. check_sw confirms
     every changed bulk file is listed somewhere in STALE, not that it is
     listed in the newest block. */
  /* v183: batch 17B. Five clips, and two sounds cleared on first hearing --
     the gamma-nasal ŋ, which γγ is in Greek, and the κν cluster τέκνον could
     not write in English. */
  'audio/vocab/416_kalos.mp3',
  'audio/vocab/420_oseph.mp3',
  'audio/vocab/431_blasphemeo.mp3',
  'audio/vocab/437_deiknumi.mp3',
  'audio/vocab/445_paraggello.mp3',
  /* v182: batch 17, built as an experiment rather than a batch. Four clips,
     all four the converter's own output and none needing an exception. */
  'audio/vocab/402_prasso.mp3',
  'audio/vocab/424_martus.mp3',
  'audio/vocab/434_biblion.mp3',
  'audio/vocab/443_apas.mp3',
  /* v181: batch 16B, and the first round a machine screened before a person
     heard it. ὑποτάσσω was caught reading its own syllable dot aloud as the
     WORD "dot" and was sent dotless instead. */
  'audio/vocab/395_apto.mp3',
  'audio/vocab/398_pente.mp3',
  'audio/vocab/401_upotasso.mp3',
  'audio/vocab/411_atanas.mp3',
  'audio/vocab/419_kauchaomai.mp3',
  /* v180: batch 16. Two clips re-cut. ἄρχων is the one worth naming: its chi is
     medial so it is written k, and it ends in `oːn` so the omega is written oʊ.
     Two rules found four batches apart, composing in one word, right first time. */
  'audio/vocab/362_thaumazo.mp3',
  'audio/vocab/407_archon.mp3',
  /* v178: batch 15B. Five clips re-cut, 363 occurrences, and the chi block gone
     for good -- chi in the MIDDLE of a word is written as a plain k. It gives
     up the breath, and it beat both the IPA that kept it and the English that
     kept it. */
  'audio/vocab/078_eiserchomai.mp3',
  'audio/vocab/326_chreia.mp3',
  'audio/vocab/349_kathizo.mp3',
  'audio/vocab/390_tessares.mp3',
  'audio/vocab/415_ous.mp3',
  /* v177: batch 15. Three clips re-cut. κράζω is the one that earned a rule:
     14B changed the ζ ligature and removed the dot in front of it at once, and
     this held the ligature fixed and varied only the dot. Dotless won. */
  'audio/vocab/224_dexios.mp3',
  'audio/vocab/308_krazo.mp3',
  'audio/vocab/385_ikanos.mp3',
  /* v171: batch 14B, and the chi block lifted. χάρις had held 14 cues and 517
     occurrences out of the IPA route since 9E on a verdict with a confound in
     it -- both of its takes carried a syllable dot, before anybody knew a dot
     could be spoken. Dotless, chi won first time.
     205_charis.mp3 is re-cut too and is NOT repeated here: it is already
     in the v163 block, from the batch-9 round that rejected it. */
  'audio/vocab/299_aspazomai.mp3',
  'audio/vocab/353_oudas.mp3',
  'audio/vocab/380_pantote.mp3',
  /* v169: batch 14. Four clips re-cut, 198 occurrences. ἱερεύς is the third
     -εύς word to want its dots taken out, so that stopped being three notes
     in a checker and became a rule. And λοιπός is the first οι anybody has
     judged — the diphthong the conversion was wrong about twice. */
  'audio/vocab/295_auid.mp3',
  'audio/vocab/310_loipos.mp3',
  'audio/vocab/313_opos.mp3',
  'audio/vocab/452_iereus.mp3',
  /* v168: batch 13B. Five clips re-cut, 767 occurrences. ὡς is the deck's 34th
     commonest word and it was put up to settle one question: a long omega at
     the end of a word recites before n and r, and this asked whether it does
     before s. It does not, so the nine cues ending that way convert as they
     stand. */
  'audio/vocab/034_os.mp3',
  'audio/vocab/209_kerusso.mp3',
  'audio/vocab/263_apokteino.mp3',
  'audio/vocab/275_karpos.mp3',
  'audio/vocab/281_grammateus.mp3',
  /* v167: batch 13. Four clips re-cut, 301 occurrences. ὕδωρ is the second
     word to show that a long omega at the end of one is recited letter by
     letter, so that stopped being an exception and became part of the rule. */
  'audio/vocab/186_pipto.mp3',
  'audio/vocab/255_udor.mp3',
  'audio/vocab/271_sabbaton.mp3',
  'audio/vocab/272_rema.mp3',
  /* v166: batch 12 and 12B. Seven clips re-cut, 739 occurrences. τέκνον is
     worth naming for what IPA is for -- English cannot begin a syllable with
     κν, so its cue wrote "knon", and an English kn has a silent k. */
  'audio/vocab/123_apostello.mp3',
  'audio/vocab/139_basileus.mp3',
  'audio/vocab/145_apothnesko.mp3',
  'audio/vocab/148_mello.mp3',
  'audio/vocab/167_teknon.mp3',
  'audio/vocab/187_epta.mp3',
  'audio/vocab/246_mallon.mp3',
  /* v165: batch 11. Five clips re-cut -- four of them only to take out the
     syllable dot that sat against their stress mark, which the voice had been
     reading aloud. */
  'audio/vocab/041_polus.mp3',
  'audio/vocab/104_poreuomai.mp3',
  'audio/vocab/110_egeiro.mp3',
  'audio/vocab/129_aion.mp3',
  'audio/vocab/198_anoigo.mp3',
  /* v164: batch 10, the first batch written in IPA. Five new words and two
     batch-9 clips improved. The two are ὁράω and πιστεύω, re-cut with the
     syllable dot before the stress taken out -- it had been read aloud twice,
     and three words in a row chose the version without it. */
  'audio/vocab/039_orao.mp3',
  'audio/vocab/062_pisteuo.mp3',
  'audio/vocab/098_kardia.mp3',
  'audio/vocab/117_palin.mp3',
  'audio/vocab/122_blepo.mp3',
  'audio/vocab/133_dunamis.mp3',
  /* v163: batch 9. Seventeen vocabulary clips re-cut, and they are bulk
     files -- a VERSION bump replaces the shell and never reaches them, so a
     phone that has already cached one would keep the old sound for ever.
     Fifteen of the seventeen changed because the cue moved from an English
     respelling to IPA, which this voice reads better than any spelling:
     ORAO's English cue had already been approved by ear and the IPA beat it.
     TOTE had no English spelling that worked at all -- `tot` is a real word
     with the right vowel and the voice read it as the first syllable of
     TOTAL. */
  'audio/vocab/013_oti.mp3',
  'audio/vocab/017_esous.mp3',
  'audio/vocab/039_orao.mp3',
  'audio/vocab/041_polus.mp3',
  'audio/vocab/045_pneuma.mp3',
  'audio/vocab/060_megas.mp3',
  'audio/vocab/062_pisteuo.mp3',
  'audio/vocab/070_aner.mp3',
  'audio/vocab/094_polis.mp3',
  'audio/vocab/095_tote.mp3',
  'audio/vocab/104_poreuomai.mp3',
  'audio/vocab/110_egeiro.mp3',
  'audio/vocab/128_otan.mp3',
  'audio/vocab/129_aion.mp3',
  'audio/vocab/143_monos.mp3',
  'audio/vocab/205_charis.mp3',
  'audio/vocab/284_exo.mp3',
  /* v156: chapter 2 rewritten for a reader who has not met the words
     yet, and chapter 1 gains the alphabet block its narration never
     had. Every lesson clip is re-cut, so all of them are evicted --
     they are bulk files and a VERSION bump does not reach them. */
  'audio/lessons/l01_01.mp3',
  'audio/lessons/l01_02.mp3',
  'audio/lessons/l01_03.mp3',
  'audio/lessons/l01_04.mp3',
  'audio/lessons/l01_05.mp3',
  'audio/lessons/l01_06.mp3',
  'audio/lessons/l01_07.mp3',
  'audio/lessons/l01_08.mp3',
  'audio/lessons/l01_09.mp3',
  'audio/lessons/l01_10.mp3',
  'audio/lessons/l01_11.mp3',
  'audio/lessons/l01_12.mp3',
  'audio/lessons/l01_13.mp3',
  'audio/lessons/l02_00.mp3',
  'audio/lessons/l02_01.mp3',
  'audio/lessons/l02_02.mp3',
  'audio/lessons/l02_03.mp3',
  'audio/lessons/l02_04.mp3',
  'audio/lessons/l02_05.mp3',
  'audio/lessons/l02_06.mp3',
  'audio/lessons/l02_07.mp3',
  'audio/lessons/l02_08.mp3',
  'audio/lessons/l02_09.mp3',
  'audio/lessons/l02_10.mp3',
  'audio/lessons/l02_11.mp3',
  'audio/lessons/l02_12.mp3',
  'audio/lessons/l02_13.mp3',
  'audio/lessons/l02_14.mp3',
  'audio/lessons/l02_15.mp3',
  'audio/lessons/l02_16.mp3',
  'audio/lessons/l02_17.mp3',
  'audio/lessons/l02_18.mp3',
  'audio/lessons/l02_19.mp3',
  'audio/lessons/l02_20.mp3',
  'audio/lessons/l02_21.mp3',
  /* v154: batch 8. Forty clips played in risk order; 34 were right
     first time. The ranking itself was the experiment and it FAILED:
     the ten with the most shapes against them had no faults and the
     ten with none had one, 0/3/2/1 across the four lots. So the work
     list stops being ordered and just gets played.
     All six faults had their remedy already sitting in an approved
     clip -- ζ- from ζωή, the helper vowel from πτωχός, the hard-g
     digraph from γινώσκω. */
  'audio/vocab/047_eis.mp3',
  'audio/vocab/118_zao.mp3',
  'audio/vocab/137_zeteo.mp3',
  'audio/vocab/203_phos.mp3',
  'audio/vocab/586_zoon.mp3',
  'audio/vocab/745_zelos.mp3',
  'audio/vocab/760_sphragis.mp3',
  'audio/vocab/777_gumnos.mp3',
  /* v153: batch 7, which was built to test the method rather than the
     clips. Ten of the 226 clips made entirely from approved spellings
     were picked as the ten places composition was LEAST likely to
     hold; seven passed, one was a bad take, and the three failures
     share one narrow shape. 223 of 226 stand, so the pile still
     needing an ear is 271 and not 497.
     θεωρέω and θεάομαι ship as ear-compromise: `thay` is the eta
     vowel where the Greek has epsilon, because every spelling that
     keeps the vowel begins with the letters t-h-e and Atlas reads
     those as the article. δέω escaped it with a COMMA, which nothing
     in this pack had used before. */
  'audio/vocab/130_archiereus.mp3',
  'audio/vocab/163_allelon.mp3',
  'audio/vocab/174_peripateo.mp3',
  'audio/vocab/302_theoreo.mp3',
  'audio/vocab/364_deo.mp3',
  'audio/vocab/477_neanias.mp3',
  'audio/vocab/485_thugater.mp3',
  'audio/vocab/606_theaomai.mp3',
  /* v152: batch 6. Twenty spellings judged, about seventy clips
     cleared, and only eight clips actually changed -- fourteen of
     the twenty were right as they stood. Three of the six failures
     named a token other than the one on trial, and two more were
     simply bad takes: the same cue rolled again came back right.
     That is now three in two rounds, which is why a rejected cue
     always returns as a control. */
  'audio/vocab/061_pistis.mp3',
  'audio/vocab/066_onoma.mp3',
  'audio/vocab/103_ostis.mp3',
  'audio/vocab/175_phobeomai.mp3',
  'audio/vocab/220_thusia.mp3',
  'audio/vocab/244_oste.mp3',
  'audio/vocab/423_eutheos.mp3',
  'audio/vocab/659_koinonia.mp3',
  /* v151: προσδοκάω, the last clip of batch 5. It needed three fixes
     at once -- the προσ- sigma the rule has required since batch 4,
     the English word `do`, and a space closed for pace. The `do`
     gate lands with it, because until now this clip was the only
     thing in the pack that would have failed it. */
  'audio/vocab/757_prosdokao.mp3',
  /* v150: batch 5 of the vocabulary audit -- 59 clips re-cued and
     re-recorded, every one heard. Six rules came out of it and each
     is now a gate in check_cues: the bare -os ending (18 clips had
     missed a fix 58 others carry a note about), `Ceye` for ai,
     `sees` for -sis, `ro`, and the English /ou/ words against au.
     These are bulk files, so a VERSION bump does not replace them
     and each has to be named. */
  'audio/vocab/097_aulos.mp3',
  'audio/vocab/146_osos.mp3',
  'audio/vocab/149_olos.mp3',
  'audio/vocab/169_arisaios.mp3',
  'audio/vocab/170_aima.mp3',
  'audio/vocab/190_pleroo.mp3',
  'audio/vocab/213_stauros.mp3',
  'audio/vocab/214_stauroo.mp3',
  'audio/vocab/225_mesos.mp3',
  'audio/vocab/230_presbuteros.mp3',
  'audio/vocab/245_anabaino.mp3',
  'audio/vocab/249_katabaino.mp3',
  'audio/vocab/267_tereo.mp3',
  'audio/vocab/279_erosoluma.mp3',
  'audio/vocab/280_daimonion.mp3',
  'audio/vocab/282_dokeo.mp3',
  'audio/vocab/283_oros.mp3',
  'audio/vocab/288_alilaia.mp3',
  'audio/vocab/301_didaskalos.mp3',
  'audio/vocab/305_toioutos.mp3',
  'audio/vocab/311_ilatos.mp3',
  'audio/vocab/331_emprosthen.mp3',
  'audio/vocab/333_phaneroo.mp3',
  'audio/vocab/337_krisis.mp3',
  'audio/vocab/346_therion.mp3',
  'audio/vocab/351_omoios.mp3',
  'audio/vocab/367_akobos.mp3',
  'audio/vocab/373_anastasis.mp3',
  'audio/vocab/376_oligos.mp3',
  'audio/vocab/387_oikodomeo.mp3',
  'audio/vocab/406_emautou.mp3',
  'audio/vocab/413_ilippos.mp3',
  'audio/vocab/429_melos.mp3',
  'audio/vocab/432_oinos.mp3',
  'audio/vocab/440_poios.mp3',
  'audio/vocab/450_anemos.mp3',
  'audio/vocab/467_eggus.mp3',
  'audio/vocab/469_suneidesis.mp3',
  'audio/vocab/497_pseudomai.mp3',
  'audio/vocab/534_katargeo.mp3',
  'audio/vocab/581_anaireo.mp3',
  'audio/vocab/601_eklektos.mp3',
  'audio/vocab/605_dokimazo.mp3',
  'audio/vocab/618_eklegomai.mp3',
  'audio/vocab/619_esaias.mp3',
  'audio/vocab/623_eudokeo.mp3',
  'audio/vocab/636_ge.mp3',
  'audio/vocab/648_epignosis.mp3',
  'audio/vocab/665_palaios.mp3',
  'audio/vocab/676_deesis.mp3',
  'audio/vocab/685_oikodome.mp3',
  'audio/vocab/704_thesauros.mp3',
  'audio/vocab/707_kerdaino.mp3',
  'audio/vocab/722_aphesis.mp3',
  'audio/vocab/724_embaino.mp3',
  'audio/vocab/732_osautos.mp3',
  'audio/vocab/766_ekteino.mp3',
  'audio/vocab/774_saulos.mp3',
  'audio/vocab/787_kleronomos.mp3',
  /* v140 adds the closed-testing prompt and changes only SHELL files --
     index.html, css/app.css, js/pwa.js, js/app.js, privacy.html -- so the
     VERSION bump replaces every one of them and nothing is added here. The
     audio entries below stay: STALE is read on every activate, and a clip
     already evicted is simply missing, which costs one refetch. */
  /* v139: ἀγνοέω, and it took six rounds because of where I was looking.
     Its ο is an omicron and every cue spelled it `no` -- an English word
     with the /ou/ of gold, which is the exact fault check_cues gates. That
     rule was written and gated an hour before I offered four fresh
     candidates that all contained the token. Five rounds went on h
     placement, binding and syllable splits: a vowel fault treated as a
     structure fault. `agnaw eh hoe` is νομίζω's own `nawmee zoh` shape,
     the aw bound forward, and the strong h disappears with it.
     The lesson is the one the batch-4 audit started from -- the cue guide
     had an answer to all ten of his complaints before those clips were
     made. A rule nobody applies is prose, whether it sits in a markdown
     file or in a checker written ninety minutes earlier.
     STALE also had ἀγνοέω twice, from v137 and v138. Deduplicated here;
     the list is read on every activate, so a repeat was harmless and
     untidy. */
  /* v138: σοφία and ἀγνοέω, the two blemishes flagged in passing.
     σοφία `soffee ah` had the vowel and was clunky; `sawfeeah` is σοφός's
     own answer transposed -- one token for the flow, the vowel spelled.
     ἀγνοέω is the first cue accepted WITH A KNOWN FAULT. Its ο is an
     omicron and `no` gives it the gold vowel, but every remedy tried came
     back at 0.63-0.91s a syllable and spelled: "None win. All the others
     here spell words/letters." It is a 22-occurrence word and the blemish
     is recorded in its cue row rather than chased.
     It also found the gate's limit: the gold-vowel rule reads only a cue's
     FIRST token, and ἀγνοέω has its `no` second. Widening it is blocked --
     of the 24 cues a wider test flags, most are false (every `hoe` is the
     -ω ending, an omega) and two of the genuine ones are already approved,
     γίνομαι and ἀποκρίνομαι. Work list, not a gate. */
  /* v137: nine clips, and the end of a rule's argument. Every rule an ear
     had settled was applied to all 593 clips nobody has heard; it changed
     FOUR of them, so regenerating the rest was not done -- it would have
     re-rolled a non-deterministic voice over clips of unknown quality
     rather than fixing anything. The sweep was still worth it: it found
     εἰ and ἤ, #37 and #51 in the deck, both cued `ay` and never heard.
     The prediction that a bare letter name would be read as the letter was
     WRONG -- both were played and kept -- and the guide now says so.
     The gold-vowel rule went the other way and is now gated: νόμος, σοφία
     and νομίζω all moved, making it five for five with χρόνος and σοφός.
     Three of those five had been PASSED in an earlier batch, before anyone
     was asking whether that o was the one in omelet. */
  /* v136: χρόνος and σοφός, and the rule that came out of them. Fraser
     re-heard two clips he had passed and found both wrong -- they had been
     judged before the omicron/omega question existed, so `crow noss` and
     `so foss` had never been asked whether that o was the one in omelet.
     Both are now closed syllables: `chronoss`, `sawfoss`.
     Those two were also the whole evidence for a line in the guide saying
     this drift could not be predicted. It could; the note is corrected and
     names three unheard words it flags, which stay a work list until an ear
     reaches them. And a fourth sighting of the `oss` fault -- a bare `oss`
     after a consonant picks up an extra letter -- IS now gated in
     check_cues, because it needs no prediction: a cue either has one or it
     does not. Its first version called `lah` and `neh` consonant-final and
     flagged three approved clips; the guide says in rule 5 that the h in
     ah/eh/oh is not a sound, so the checker was wrong and the pack right. */
  /* v135: πρόβατον alone. Its stressed omicron was lengthening toward an
     omega, and closing the syllable with a doubled beta forces it short --
     `pro bah ton` -> `probbah ton`, the third time that mechanism has
     worked after πρός and the four προσ- compounds. The guide records it
     as a remedy and explicitly not as a rule: the obvious predictor, that
     a cue drifts long when it spells an English gold-vowel word, is false,
     and χρόνος `crow noss`, σοφός `so foss` and πρό `pro` are the three
     heard clips that disprove it. */
  /* v134: the four προσ- clips. The rule the guide gave for them was right
     and its reason was wrong -- it said `pro` is "the omega sound, as in
     professional", and professional has a schwa in that syllable. Tested
     over seven words: the four προσ- ones moved to `pross`, because a bare
     `pro` drops the sigma; πρό, πρόβατον and πρῶτος all kept what they had.
     So it is the sigma and not the vowel, and check_cues holds that
     positionally now. The same experiment found a real limit, which the
     guide records: ο and ω are separated everywhere the pack can manage it
     and cannot be in `pro` -- πρό and πρῶτος are spelled the same, were
     heard side by side against φωνή and τόπος, and both were kept. */
  /* v133: batch 4 closed, and sixteen clips changed. Ten flags in fifty --
     but the finding is not the count. Every one of the ten had a cause
     already written in the cue guide before the clip was made, and four
     were spellings a previous batch had fixed in ONE word while leaving
     the other words carrying them: `keye` was replaced for καινός on the
     10th and shipped again in καιρός on the 11th. tools/check_cues.py is
     the answer to that and holds all 818 against what an ear rejected.
     Two other things settled here: bare `gee` is spoken as the letter G,
     which is why ἀναγινώσκω said it, and `ghee` beat Fraser's own `gehn`
     -- so the h is the fix and not the syllable division. And speed, a
     number on the request that this project had never used in four
     rounds, fixed a clip that was right and too slow. */
  /* v121, like v120, changes data/lessons.js only. It is in SHELL, so
     the VERSION bump replaces it and nothing here needs touching. */
  /* v120 changes data/lessons.js only, which is precached in SHELL and
     so is replaced by the VERSION bump. No bulk file changed, so the
     v119 entries below stay: STALE is read on every activate and a
     clip already evicted is simply missing, which costs one refetch. */
  /* v119: batch 3 closed. Six flags in fifty, against thirty-one in
     batch 2 -- and three of the six were faults already settled,
     sitting in cues no rule reached: νέος bound so its -ος never
     stood alone, καινός with the αι diphthong, ἅγιος with a soft g.
     πρός needed no new cue at all: the same one rolled again, which
     is now the second time that has been the answer. And ἀκάθαρτος
     was not re-cued -- the take was right and only slow, at 2.73 s
     against a 1.80 median for the pack's 177 other four-syllable
     clips, so it is the same recording at the median tempo. */
  'audio/vocab/022_pros.mp3',                        // πρός
  'audio/vocab/064_agios.mp3',                       // ἅγιος
  'audio/vocab/369_kainos.mp3',                      // καινός
  'audio/vocab/487_ischuros.mp3',                    // ἰσχυρός
  'audio/vocab/488_neos.mp3',                        // νέος
  'audio/vocab/495_manthano.mp3',                    // μανθάνω
  'audio/vocab/444_akathartos.mp3',                  // ἀκάθαρτος
  'audio/vocab/165_ophthalmos.mp3',                // ὀφθαλμός
  'audio/vocab/192_dikaioo.mp3',                   // δικαιόω
  'audio/vocab/193_kairos.mp3',                    // καιρός
  'audio/vocab/194_proseuchomai.mp3',              // προσεύχομαι
  'audio/vocab/273_ploion.mp3',                    // πλοῖον
  'audio/vocab/312_chronos.mp3',                   // χρόνος
  'audio/vocab/316_paidion.mp3',                   // παιδίον
  'audio/vocab/356_epiginosko.mp3',                // ἐπιγινώσκω
  'audio/vocab/391_logizomai.mp3',                 // λογίζομαι
  'audio/vocab/392_perisseuo.mp3',                 // περισσεύω
  'audio/vocab/408_paraginomai.mp3',               // παραγίνομαι
  'audio/vocab/441_echthros.mp3',                  // ἐχθρός
  'audio/vocab/442_elios.mp3',                     // ἥλιος
  'audio/vocab/446_anaginosko.mp3',                // ἀναγινώσκω
  'audio/vocab/506_ana.mp3',                       // ἀνά
  'audio/vocab/672_epairo.mp3',                    // ἐπαίρω
  'audio/vocab/191_proserchomai.mp3',              // προσέρχομαι
  'audio/vocab/256_prosopon.mp3',                  // πρόσωπον
  'audio/vocab/291_proskuneo.mp3',                 // προσκυνέω
  'audio/vocab/417_proseuche.mp3',                 // προσευχή
  'audio/vocab/394_probaton.mp3',                   // πρόβατον
  'audio/vocab/486_sofos.mp3',                      // σοφός
  'audio/vocab/029_poieo.mp3',                     // ποιέω
  'audio/vocab/035_ei.mp3',                        // εἰ
  'audio/vocab/049_e.mp3',                         // ἤ
  'audio/vocab/079_nomos.mp3',                     // νόμος
  'audio/vocab/206_sophia.mp3',                    // σοφία
  'audio/vocab/233_eleeo.mp3',                     // ἐλεέω
  'audio/vocab/427_metanoeo.mp3',                  // μετανοέω
  'audio/vocab/617_agnoeo.mp3',                    // ἀγνοέω
  'audio/vocab/790_nomizo.mp3',                    // νομίζω
];

const SHELL = [
  /* Only index.html — never also '.'. Precaching both stores two copies of
     the shell under different keys, and a CDN can hand back a stale one for
     the directory URL. Navigations are routed to this entry below, so there
     is exactly one shell and it cannot drift. */
  'index.html',
  /* Play requires the privacy policy to be reachable from inside the app, and
     an in-app link that fails on a train is not reachable. It has a .html
     extension, so the navigation router below leaves it alone rather than
     handing back the shell. */
  'privacy.html',
  'css/app.css',
  'js/app.js',
  'js/report.js',
  'js/pwa.js',
  'js/greek.js',
  'js/audio.js',
  'js/gnt.js',
  'js/icons.js',
  'js/keys.js',
  'js/write.js',
  'js/grid.js',
  'js/clause.js',
  'js/lesson_audio.js',
  'js/sync.js',
  'data/vocab.js',
  'data/lessons.js',
  'data/readings.js',
  'data/audio.js',
  'data/examples.js',
  'data/gnt/manifest.json',
  'data/offline.json',
  'data/paradigms.js',
  'data/terms.js',
  'data/lexicon.js',
  'data/forms.js',
  'data/clauses.js',
  'data/lesson_audio.js',
  'manifest.webmanifest',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/maskable-512.png',
  'audio/erasmian-alphabet-chart.pdf',
  /* 42 shared lexical forms — 520KB, small enough to always have */
  'audio/forms/f01_he.mp3',
  'audio/forms/f02_ho.mp3',
  'audio/forms/f03_to.mp3',
  'audio/forms/f04_ouk.mp3',
  'audio/forms/f05_ouch.mp3',
  'audio/forms/f06_he_rel.mp3',
  'audio/forms/f07_ho_rel.mp3',
  'audio/forms/f08_pasa.mp3',
  'audio/forms/f09_pan.mp3',
  'audio/forms/f10_ex.mp3',
  'audio/forms/f11_ti_int.mp3',
  'audio/forms/f12_ti_ind.mp3',
  'audio/forms/f13_polle.mp3',
  'audio/forms/f14_polu.mp3',
  'audio/forms/f15_patros.mp3',
  'audio/forms/f16_mia.mp3',
  'audio/forms/f17_hen.mp3',
  'audio/forms/f18_ges.mp3',
  'audio/forms/f19_megale.mp3',
  'audio/forms/f20_mega.mp3',
  'audio/forms/f21_oudemia.mp3',
  'audio/forms/f22_ouden.mp3',
  'audio/forms/f23_andros.mp3',
  'audio/forms/f24_gunaikos.mp3',
  'audio/forms/f25_cheiros.mp3',
  'audio/forms/f26_hetis.mp3',
  'audio/forms/f27_ho_ti.mp3',
  'audio/forms/f28_sarkos.mp3',
  'audio/forms/f29_podos.mp3',
  'audio/forms/f30_metros.mp3',
  'audio/forms/f31_photos.mp3',
  'audio/forms/f32_haute.mp3',
  'audio/forms/f33_touto.mp3',
  'audio/forms/f34_medemia.mp3',
  'audio/forms/f35_meden.mp3',
  'audio/forms/f36_hudatos.mp3',
  'audio/forms/f37_puros.mp3',
  'audio/forms/f38_tria.mp3',
  'audio/forms/f39_ta.mp3',
  'audio/forms/f40_orous.mp3',
  'audio/forms/f41_nuktos.mp3',
  'audio/forms/f42_otos.mp3',
  'audio/ui/correct.mp3',
  'audio/ui/wrong.mp3',

  /* pronunciation clips — 540KB, cached so audio works offline */
  'audio/clips/01_alpha.mp3',
  'audio/clips/02_beta.mp3',
  'audio/clips/03_gamma.mp3',
  'audio/clips/04_delta.mp3',
  'audio/clips/05_epsilon.mp3',
  'audio/clips/06_zeta.mp3',
  'audio/clips/07_eta.mp3',
  'audio/clips/08_theta.mp3',
  'audio/clips/09_iota.mp3',
  'audio/clips/10_kappa.mp3',
  'audio/clips/11_lambda.mp3',
  'audio/clips/12_mu.mp3',
  'audio/clips/13_nu.mp3',
  'audio/clips/14_xi.mp3',
  'audio/clips/15_omicron.mp3',
  'audio/clips/16_pi.mp3',
  'audio/clips/17_rho.mp3',
  'audio/clips/18_sigma.mp3',
  'audio/clips/19_tau.mp3',
  'audio/clips/20_upsilon.mp3',
  'audio/clips/21_phi.mp3',
  'audio/clips/22_chi.mp3',
  'audio/clips/23_psi.mp3',
  'audio/clips/24_omega.mp3',
  'audio/clips/d01_ai.mp3',
  'audio/clips/d02_ei.mp3',
  'audio/clips/d03_oi.mp3',
  'audio/clips/d04_ui.mp3',
  'audio/clips/d05_au.mp3',
  'audio/clips/d06_eu.mp3',
  'audio/clips/d07_hu.mp3',
  'audio/clips/d08_ou.mp3'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c =>
    c.addAll(SHELL.map(u => new Request(u, { cache: 'reload' })))));
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();

    /* One-time migration off the single-cache layout: carry the bulk files
       out of the old cache instead of sweeping them and re-downloading
       9.5MB. Guarded, because a failure here must not stop the worker
       activating — the fill would recover it, just slowly. */
    try {
      const old = keys.filter(k => k !== CACHE && k !== BULK && k.startsWith('koine-v'));
      if (old.length) {
        const bulkCache = await caches.open(BULK);
        for (const k of old) {
          const c = await caches.open(k);
          for (const req of await c.keys()) {
            if (!isBulkUrl(req.url)) continue;
            if (await bulkCache.match(req)) continue;
            const r = await c.match(req);
            if (r) await bulkCache.put(req, r);
          }
        }
      }
    } catch (e) { /* fall through to a normal fill */ }

    /* Drop the re-recorded clips so the fill below pulls them again. */
    try {
      const bulkCache = await caches.open(BULK);
      for (const u of STALE) {
        await bulkCache.delete(u);
        await bulkCache.delete(u, { ignoreSearch: true });
      }
    } catch (e) { /* nothing cached yet */ }

    await Promise.all(keys.filter(k => k !== CACHE && k !== BULK).map(k => caches.delete(k)));
    await self.clients.claim();
    fillBulk();                       // not awaited: the app is usable already
  })());
});

/* Everything else — word clips and the New Testament — pulled in the
   background once the app is running. Deliberately not part of the install:
   cache.addAll is all-or-nothing, and one failed response among 500 would
   stop the worker installing at all. Here a failure costs one file.

   Re-running is cheap because anything already cached is skipped, so the
   page asks for a top-up on every load and an interrupted fill resumes. */
let filling = false;

async function post(msg) {
  const cs = await self.clients.matchAll({ includeUncontrolled: true });
  cs.forEach(c => c.postMessage(msg));
}

async function fillBulk() {
  if (filling) return;
  filling = true;
  try {
    /* The manifest is a SHELL entry, so it is read from CACHE. Reading it
       from BULK would miss, fall through to fetch(), and throw when offline
       — and then no fill would ever run. */
    const cache = await caches.open(CACHE);
    const bulkCache = await caches.open(BULK);
    const res = await cache.match('data/offline.json') || await fetch('data/offline.json');
    const { bulk } = await res.json();

    const queue = bulk.slice();
    let done = 0, failed = 0;
    const total = bulk.length;

    const worker = async () => {
      while (queue.length) {
        const url = queue.shift();
        try {
          if (!(await bulkCache.match(url))) {
            const r = await fetch(url);
            if (r.status === 200) await bulkCache.put(url, r);
            else failed++;
          }
        } catch (e) { failed++; }
        done++;
        if (done % 20 === 0) post({ type: 'offline-progress', done: done - failed, total, failed });
      }
    };
    // Six at a time: enough to be quick, few enough to leave the network
    // responsive if the app is being used while this runs.
    await Promise.all(Array.from({ length: 6 }, worker));

    /* One retry pass. The first requests go out while the worker is still
       activating and a couple reliably lose that race, so without this a
       fresh install finishes a file or two short and only recovers on the
       next visit — which is not what "offline by default" should mean. */
    if (failed) {
      const retry = [];
      for (const url of bulk) if (!(await bulkCache.match(url))) retry.push(url);
      for (const url of retry) {
        try {
          const r = await fetch(url);
          if (r.status === 200) { await bulkCache.put(url, r); failed--; }
        } catch (e) { /* leave it for the next load */ }
      }
    }
    post({ type: 'offline-progress', done: done - failed, total, failed, complete: failed === 0 });
  } catch (e) {
    post({ type: 'offline-progress', error: true });
  } finally {
    filling = false;
  }
}

self.addEventListener('message', e => {
  if (e.data === 'skip-waiting') self.skipWaiting();
  if (e.data === 'ensure-offline') e.waitUntil(fillBulk());
  if (e.data === 'offline-status') e.waitUntil(reportStatus());
  /* The version lives here and nowhere else. A problem report asks for
     it rather than carrying a copy that can go stale. */
  if (e.data === 'version') post({ type: 'version', version: VERSION });
});

async function reportStatus() {
  try {
    const cache = await caches.open(CACHE);       // the manifest is a SHELL entry
    const bulkCache = await caches.open(BULK);
    const res = await cache.match('data/offline.json') || await fetch('data/offline.json');
    const { bulk } = await res.json();
    let have = 0;
    for (const u of bulk) if (await bulkCache.match(u)) have++;
    post({ type: 'offline-status', have, total: bulk.length });
  } catch (e) {
    post({ type: 'offline-status', error: true });
  }
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);

    // Every navigation resolves to the one cached shell — but only real page
    // navigations. A target="_blank" link to a file (the alphabet PDF) also
    // arrives as mode:'navigate', and was being handed index.html instead.
    const leaf = new URL(req.url).pathname.split('/').pop();
    if (req.mode === 'navigate' && !/\.[a-z0-9]+$/i.test(leaf)) {
      const shell = await cache.match('index.html');
      if (shell) return shell;
      try { return await fetch(req); } catch (err) { return Response.error(); }
    }

    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;

    // Word clips and New Testament books are held separately, so that a
    // version bump does not cost 9.5MB. A runtime miss is stored in
    // whichever of the two it belongs to.
    const bulkCache = isBulkUrl(req.url) ? await caches.open(BULK) : null;
    if (bulkCache) {
      const hit = await bulkCache.match(req, { ignoreSearch: true });
      if (hit) return hit;
    }

    const res = await fetch(req);
    if (res.status === 200 && res.type === 'basic') (bulkCache || cache).put(req, res.clone());
    return res;
  })());
});
