# -*- coding: utf-8 -*-
"""chapters.html -- what each of the 27 chapters teaches, as a plain page.

    python tools/build_chapters_page.py            # write chapters.html
    python tools/build_chapters_page.py --check    # exit 1 if it is stale

WHY. The app draws its chapters with JavaScript, so a search engine sees none
of them. Someone searching for "second aorist" or "genitive absolute" should
be able to find a page that says which chapter teaches it. This page lists
each chapter's title, its one-line summary and the headings inside it -- the
topics as the chapter itself names them.

GENERATED, NEVER EDITED BY HAND. Everything on it comes from data/lessons.js
(title, summary, headings, number of parts) and data/lesson_audio.js (which
chapters are read aloud), so it cannot say something the chapters do not.
check_chapters_page runs this with --check and fails when a lesson has changed
and the page has not been rebuilt.
"""
import html
import io
import json
import os
import re
import subprocess
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "chapters.html")

TAG = re.compile(r"<[^>]+>")
HEAD = re.compile(r"<(h2|h3)\b[^>]*>(.*?)</\1>", re.S)


def lessons():
    js = ("const fs=require('fs'),vm=require('vm');const c=vm.createContext({});"
          "vm.runInContext(fs.readFileSync('data/lessons.js','utf8'),c);"
          "process.stdout.write(vm.runInContext('JSON.stringify(LESSONS.map("
          "l=>({id:l.id,t:l.t,s:l.s,body:l.body})))',c));")
    r = subprocess.run(["node", "-e", js], cwd=ROOT, capture_output=True,
                       text=True, encoding="utf-8")
    if r.returncode or not r.stdout:
        sys.exit("could not read data/lessons.js:\n" + (r.stderr or ""))
    return json.loads(r.stdout)


def narrated():
    """Chapters with narration, from the file the app loads."""
    p = os.path.join(ROOT, "data", "lesson_audio.js")
    if not os.path.isfile(p):
        return set()
    s = io.open(p, encoding="utf-8").read()
    m = re.search(r"const LESSON_AUDIO = (\[.*\]);\s*$", s, re.S)
    return {r["ch"] for r in json.loads(m.group(1))} if m else set()


def text(fragment):
    return " ".join(html.unescape(TAG.sub(" ", fragment)).split())


def page():
    ls = lessons()
    aloud = narrated()
    items = []
    for l in ls:
        heads = [text(h) for _t, h in HEAD.findall(l["body"])]
        heads = [h for h in dict.fromkeys(heads) if h]
        parts = len(HEAD.findall(l["body"])) + 1
        badge = ('<span class="badge">Read aloud</span>'
                 if l["id"] in aloud else "")
        topics = ("<ul>%s</ul>" % "".join("<li>%s</li>" % html.escape(h)
                                          for h in heads)) if heads else ""
        items.append(
            '<section class="ch" id="chapter-%d">\n'
            '  <h2><span class="n">Chapter %d</span> %s %s</h2>\n'
            '  <p class="s">%s</p>\n  %s\n</section>'
            % (l["id"], l["id"], html.escape(l["t"]), badge,
               html.escape(l["s"] or ""), topics))
    return TEMPLATE % {"count": len(ls), "aloud": len(aloud),
                       "items": "\n".join(items)}


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>What the chapters cover — Everyday Koine</title>
<meta name="description" content="The %(count)d chapters of Everyday Koine, a New Testament Greek course: what each one teaches, from the alphabet and the verb system to participles, the subjunctive and -μι verbs.">
<meta name="theme-color" content="#141b2b">
<link rel="icon" href="icons/icon-192.png">
<link rel="canonical" href="https://everydaykoine.app/chapters.html">
<!-- GENERATED by tools/build_chapters_page.py from data/lessons.js.
     Do not edit by hand: check_chapters_page fails when this goes stale. -->
<style>
  :root{
    --bg:#141b2b; --surface:#1e2739; --line:#38445d;
    --text:#e9e5da; --muted:#97a1b5; --gold:#d4a537; --gold-ink:#1b1406;
    --ui:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",sans-serif;
  }
  *{box-sizing:border-box}
  body{margin:0; padding:2.25rem 1rem 5rem; background:var(--bg); color:var(--text);
       font:16px/1.6 var(--ui)}
  main{max-width:44rem; margin:0 auto}
  a{color:var(--gold)}
  .back{display:inline-block; margin-bottom:1.5rem; color:var(--muted); font-size:.9rem}
  h1{font-size:1.9rem; line-height:1.2; margin:0 0 .6rem; text-wrap:balance}
  .lede{margin:0 0 1rem}
  .open{display:inline-block; background:var(--gold); color:var(--gold-ink); font-weight:700;
        text-decoration:none; padding:.7rem 1.2rem; border-radius:12px}
  .ch{background:var(--surface); border:1px solid var(--line); border-radius:12px;
      padding:.95rem 1.1rem; margin:.8rem 0}
  .ch h2{font-size:1.05rem; margin:0; line-height:1.35; text-wrap:balance}
  .n{color:var(--gold); font-variant-numeric:tabular-nums; margin-right:.25rem}
  .s{margin:.25rem 0 .2rem; color:var(--muted)}
  .ch ul{margin:.45rem 0 0; padding-left:1.1rem; font-size:.93rem}
  .ch li{margin:.15rem 0}
  .badge{display:inline-block; font-size:.72rem; font-weight:600; letter-spacing:.03em;
         color:var(--gold); border:1px solid var(--gold); border-radius:999px;
         padding:.05rem .5rem; margin-left:.3rem; vertical-align:.15em}
  footer{margin-top:2.5rem; padding-top:1.1rem; border-top:1px solid var(--line);
         color:var(--muted); font-size:.86rem}
</style>
</head>
<body>
<main>
  <a class="back" href="about.html">&lsaquo; About Everyday Koine</a>
  <h1>What the chapters cover</h1>
  <p class="lede">%(count)d chapters take you from the alphabet to reading the
  Greek New Testament. Each comes in short parts with questions along the way,
  and %(aloud)d are read aloud so far. The topics under each chapter are its
  own section headings.</p>
  <a class="open" href="/?go=learn">Open the chapters in the app</a>
%(items)s
  <footer>
    <p><a href="/">Open the app</a> · <a href="about.html">About</a> ·
    <a href="privacy.html">Privacy policy</a> ·
    <a href="mailto:support@everydaykoine.app">support@everydaykoine.app</a></p>
  </footer>
</main>
</body>
</html>
"""


if __name__ == "__main__":
    want = page()
    if "--check" in sys.argv:
        have = io.open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if have != want:
            print("chapters.html is stale -- run python tools/build_chapters_page.py")
            sys.exit(1)
        print("chapters.html matches the lessons")
        sys.exit(0)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(want)
    print("wrote chapters.html")
