# -*- coding: utf-8 -*-
"""chapters.html against the lessons it is built from.

    python tools/check_chapters_page.py

The page is generated by tools/build_chapters_page.py from data/lessons.js
and data/lesson_audio.js. A chapter retitled, a section added, or a chapter
newly read aloud, and the page would go on saying the old thing to every
search engine that reads it. This rebuilds it in memory and fails if the file
on disk differs.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
r = subprocess.run([sys.executable, os.path.join(ROOT, "tools",
                                                 "build_chapters_page.py"),
                    "--check"], cwd=ROOT)
sys.exit(r.returncode)
